//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STBR_Framework.InternalSystem.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormsFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormsFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STBR_Framework.InternalSystem.Forms.FormsFiles", typeof(FormsFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Manutenção Base de Dados&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;494&quot; height=&quot;299&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string frmBaseDados {
            get {
                return ResourceManager.GetString("frmBaseDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;&quot; title=&quot;Info Addon&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;366&quot; height=&quot;181&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;2&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;DT_Infos&quot;&gt;
        ///              &lt;Columns&gt;
        ///                &lt;Column [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string frmInfo {
            get {
                return ResourceManager.GetString("frmInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;&quot; title=&quot;Adicionar novo campo&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;326&quot; height=&quot;131&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/db [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string frmNewField {
            get {
                return ResourceManager.GetString("frmNewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;&quot; title=&quot;Nova Tabela&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;301&quot; height=&quot;118&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/dbdatasourc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string frmNewTable {
            get {
                return ResourceManager.GetString("frmNewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;&quot; title=&quot;Tabelas &amp;amp; Campos&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;935&quot; height=&quot;628&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;DT_Tabela&quot;&gt;
        ///              &lt;Columns&gt;
        ///             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string frmTableFields {
            get {
                return ResourceManager.GetString("frmTableFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;4&quot; BorderStyle=&quot;4&quot; uid=&quot;&quot; title=&quot;Registro UDO&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;573&quot; height=&quot;369&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables&gt;
        ///            &lt;DataTable Uid=&quot;DT_Udo&quot;&gt;
        ///              &lt;Columns&gt;
        ///                &lt;Column [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string frmUdo {
            get {
                return ResourceManager.GetString("frmUdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-16&quot;?&gt;
        ///&lt;Application&gt;
        ///  &lt;forms&gt;
        ///    &lt;action type=&quot;add&quot;&gt;
        ///      &lt;form appformnumber=&quot;-1&quot; FormType=&quot;-1&quot; type=&quot;0&quot; BorderStyle=&quot;0&quot; uid=&quot;&quot; title=&quot;Form Template Voraz&quot; visible=&quot;1&quot; default_button=&quot;&quot; pane=&quot;1&quot; color=&quot;0&quot; left=&quot;370&quot; top=&quot;127&quot; width=&quot;384&quot; height=&quot;297&quot; client_width=&quot;&quot; client_height=&quot;&quot; AutoManaged=&quot;1&quot; SupportedModes=&quot;15&quot; ObjectType=&quot;&quot; mode=&quot;3&quot;&gt;
        ///        &lt;datasources&gt;
        ///          &lt;DataTables /&gt;
        ///          &lt;dbdatasources&gt;
        ///            &lt;action type=&quot;add&quot; /&gt;
        ///          &lt;/dbd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string frmWeb {
            get {
                return ResourceManager.GetString("frmWeb", resourceCulture);
            }
        }
    }
}
